services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    env_file: .env
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - wordpress_data:/var/www/html

  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: always
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file: .env

  db:
    image: mariadb:11.4
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .env

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    entrypoint: wp
    command: "--info"
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
    name: wordpress_data
  mysql_data:
    name: mysql_data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
